### ISSUE TITLE
“cannot import name email_re”

### ISSUE THREAD

**Issue by cwhits** [uw-it-aca/spacescout_web#29]
It appears that email_re was removed from Django about a year ago (or I'm doing something completely wrong). Loading the web interface now gives the error: 
````
ImportError at /
cannot import name email_re
Request Method:	GET
Request URL:	http://localhost:8001/
Django Version:	1.6.11
Exception Type:	ImportError
Exception Value:	cannot import name email_re
Exception Location:	/web_apps/apps/spaces/spacescout_builds/web_proj/spacescout_web/forms/share.py in <module>, line 16
Python Executable:	/bin/python
Python Version:	2.7.5

In template /web_apps/apps/spaces/spacescout_builds/web_proj/spacescout_web/templates/spacescout_web/base-desktop.html, error at line 145
cannot import name email_re
````

**Comment by abztrakt** [comment]
Currently, SpaceScout is only known to work with Django 1.4, which should still have email_re in django.core.validators. We'd like to update things to get them working with newer versions of Django, but haven't had a chance to carve out time for it yet. If you can run things under 1.4 for now, you shouldn't have any problems.

**Comment by cwhits** [comment]
Running under 1.4 gives me an error with compress:
'compress' is not a valid tag library: ImportError raised loading compressor.templatetags.compress: cannot import name six

Unfortunately, python really isn't my thing :(

**Comment by abztrakt** [comment]
Did you get all of the requirements for the project installed successfully? That error suggests to me (without having been able to reproduce it) that django-compressor or it's dependencies didn't get installed. Assuming you've got pip installed:

pip install -r spacescout_web/base-requirements.txt
or just try:
pip install django-compressor

Scan the output to see if you can spot any errors that would suggest that not everything installed successfully.

(Again, if I can find time) I've got hopes to do some restructuring of this project in the future to make it a bit easier to install.

**Comment by cwhits** [comment]
I'm not really sure what the issue was but I clearly was missing *something*. I set up a Cent VM with Vagrant, ran fabfile.py and everything worked as expected.
